import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Mail, Paperclip } from "lucide-react";
import { type } from "arktype";
import {
  InferenceEvent,
  type InferenceEvent as ValidInferenceEvent,
} from "@interchange/types/runtime";
import { MailResponse, InferenceTurnResponse } from "@interchange/types";

import { MutationError } from "@/components/mutation-error";
import {
  instanceDetailQuery,
  stopInstanceMutation,
} from "@/lib/queries/tenants";
import { api, openStream } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const sessionEndedEvent = type({ type: "'session.ended'" });

const MailDeliveredEvent = type({
  type: "'mail.delivered'",
  data: {
    id: "string",
    direction: "'inbound' | 'outbound'",
    "from?": type({
      name: "string | null",
      email: "string",
    }).array(),
    "to?": type({
      name: "string | null",
      email: "string",
    }).array(),
    "subject?": "string | null",
    "sentAt?": "string | null",
    bodyValues: "Record<string, unknown>",
    textBody: type({
      partId: "string",
      type: "string",
    }).array(),
    "htmlBody?": type({
      partId: "string",
      type: "string",
    }).array(),
    "attachments?": type({
      blobId: "string",
      "name?": "string | null",
      type: "string",
      size: "number",
    }).array(),
    headers: "Record<string, string>",
    receivedAt: "string",
  },
});

const TurnCommittedEvent = type({
  type: "'turn.committed'",
  data: {
    turnId: "string",
    status: "'completed' | 'failed'",
    text: "string",
    hadError: "boolean",
    errors: type({
      category: "string",
      message: "string",
    }).array(),
    toolErrors: type({
      name: "string",
      content: "string",
    }).array(),
  },
});

function StatusBadge({ status }: { status: string }) {
  const variant =
    status === "running"
      ? "secondary"
      : status === "error"
        ? "destructive"
        : "outline";
  return <Badge variant={variant}>{status}</Badge>;
}

function Row({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="grid grid-cols-[160px_1fr] border-b last:border-b-0">
      <dt className="border-r bg-muted/50 px-4 py-3 text-sm font-medium text-muted-foreground">
        {label}
      </dt>
      <dd className="px-4 py-3 text-sm">{children}</dd>
    </div>
  );
}

function parseFromHeader(from: string): string {
  const match = from.match(/^"(.+)"\s+<.+>$/);
  if (match && match[1]) return match[1];
  const local = from.split("@")[0];
  return local ?? from;
}

function extractBodyText(
  bodyValues: Record<string, unknown>,
  textBody: { partId: string }[],
): string {
  const firstTextPart = textBody[0];
  if (!firstTextPart) return "";
  const bodyValue = bodyValues[firstTextPart.partId];
  if (
    typeof bodyValue === "object" &&
    bodyValue !== null &&
    "value" in bodyValue
  ) {
    const v = (bodyValue as { value?: unknown }).value;
    if (typeof v === "string") return v;
  }
  return "";
}

function formatAddress(addr: { name: string | null; email: string }): string {
  return addr.name ?? addr.email;
}

type MailAddress = { name: string | null; email: string };

type ChatMessage =
  | {
      kind: "mail";
      id: string;
      role: "user" | "assistant";
      content: string;
      sender: MailAddress;
      recipients: MailAddress[];
      timestamp: string;
      attachments: MailResponse["attachments"];
      isError?: boolean;
    }
  | {
      kind: "turn";
      turnId: string;
      content: string;
      timestamp: string;
      isError?: boolean;
      errors?: { category: string; message: string }[];
      toolErrors?: { name: string; content: string }[];
    };

function isAgentAddress(email: string): boolean {
  const local = email.split("@")[0];
  return !!local && local.startsWith("ins_");
}

// Inbound mail is always shown. Outbound mail is only shown when the primary
// recipient is an agent instance (inter-agent mail). Outbound mail to non-agent
// addresses (connector replies to humans) is suppressed because turn.committed
// already provides that content as a committed turn in the timeline.
export function shouldShowMail(data: {
  direction: "inbound" | "outbound";
  to?: { name: string | null; email: string }[];
}): boolean {
  if (data.direction === "inbound") return true;
  const first = data.to?.[0];
  if (!first) return false;
  return isAgentAddress(first.email);
}

// Agent instance addresses are "<instanceId>@<domain>" where instanceId
// is generated by generateId("instance") — always prefixed with "ins_".
function resolveAgentAddress(
  addr: MailAddress,
): { instanceId: string; label: string } | null {
  const local = addr.email.split("@")[0];
  if (!local || !local.startsWith("ins_")) return null;
  return { instanceId: local, label: formatAddress(addr) };
}

function resolveAgentRecipient(
  recipients: MailAddress[],
): { instanceId: string; label: string } | null {
  const first = recipients[0];
  if (!first) return null;
  return resolveAgentAddress(first);
}

type AgentActivity =
  | { type: "inferring" }
  | { type: "tool_call"; name: string }
  | { type: "tool_running"; name: string };

const instanceMessages = new Map<string, ChatMessage[]>();
const instanceStreaming = new Map<string, string>();
const instanceActivity = new Map<string, AgentActivity | null>();

function getMessages(instanceId: string): ChatMessage[] {
  const existing = instanceMessages.get(instanceId);
  if (existing) return existing;
  const fresh: ChatMessage[] = [];
  instanceMessages.set(instanceId, fresh);
  return fresh;
}

function getStreaming(instanceId: string): string {
  return instanceStreaming.get(instanceId) ?? "";
}

function clearInstanceState(instanceId: string) {
  instanceMessages.delete(instanceId);
  instanceStreaming.delete(instanceId);
  instanceActivity.delete(instanceId);
}

function mailToMessage(mail: MailResponse): ChatMessage {
  const isFromAgent = mail.direction === "outbound";
  const role: "user" | "assistant" = isFromAgent ? "assistant" : "user";
  const firstSender = mail.from[0];
  const sender: MailAddress = firstSender ?? { name: null, email: "unknown" };
  const content = extractBodyText(mail.bodyValues, mail.textBody);

  return {
    kind: "mail",
    id: mail.id,
    role,
    content,
    sender,
    recipients: mail.to,
    timestamp: mail.receivedAt,
    attachments: mail.attachments,
  };
}

function turnToMessage(turn: InferenceTurnResponse): ChatMessage | null {
  const textParts = turn.parts.filter(
    (p): p is typeof p & { content: string } =>
      p.type === "text" &&
      typeof p.content === "string" &&
      p.content.length > 0,
  );

  const errors: { category: string; message: string }[] = turn.parts
    .filter(
      (p): p is typeof p & { content: string } =>
        p.type === "error" &&
        typeof p.content === "string" &&
        p.content.length > 0,
    )
    .map((p) => ({
      category:
        typeof p.metadata?.category === "string"
          ? p.metadata.category
          : "unknown",
      message: p.content,
    }));

  const callNames = new Map<string, string>();
  for (const p of turn.parts) {
    if (
      p.type === "tool" &&
      p.metadata?.kind === "call" &&
      typeof p.metadata.callId === "string" &&
      typeof p.metadata.name === "string"
    ) {
      callNames.set(p.metadata.callId, p.metadata.name);
    }
  }

  const toolErrors: { name: string; content: string }[] = turn.parts
    .filter(
      (p) =>
        p.type === "tool" &&
        p.metadata?.kind === "result" &&
        p.metadata?.isError === true,
    )
    .map((p) => {
      const callId =
        typeof p.metadata?.callId === "string" ? p.metadata.callId : "";
      const name = callNames.get(callId) ?? callId;
      const raw = p.metadata?.content;
      const content = typeof raw === "string" ? raw : JSON.stringify(raw);
      return { name, content };
    });

  if (textParts.length === 0 && errors.length === 0 && toolErrors.length === 0)
    return null;

  const rawContent = textParts.map((p) => p.content).join("");
  const isError = turn.status === "failed";
  const content =
    rawContent || (isError ? "An error occurred during inference." : "");

  return {
    kind: "turn",
    turnId: turn.id,
    content,
    timestamp: turn.startedAt,
    ...(isError ? { isError: true } : {}),
    ...(errors.length > 0 ? { errors } : {}),
    ...(toolErrors.length > 0 ? { toolErrors } : {}),
  };
}

export function TenantInstanceDetailPage() {
  const { tenantId, instanceId } = useParams({ strict: false }) as {
    tenantId: string;
    instanceId: string;
  };
  const queryClient = useQueryClient();

  const { data: instance, isLoading } = useQuery(
    instanceDetailQuery(tenantId, instanceId),
  );

  const isRunning = instance?.status === "running";
  const displayStatus = isRunning
    ? (instance?.runtimeStatus ?? "running")
    : (instance?.status ?? "unknown");

  const [, forceRender] = useState(0);
  const rerender = () => forceRender((n) => n + 1);

  const [chatInput, setChatInput] = useState("");
  const [isSending, setIsSending] = useState(false);
  const chatScrollRef = useRef<HTMLDivElement>(null);
  const chatPinnedRef = useRef(true);

  // Hydrate chat history from the hub's DB on mount/reload.
  useEffect(() => {
    if (!isRunning) return;
    if (getMessages(instanceId).length > 0) return;

    let cancelled = false;

    void (async () => {
      const [mailRes, turnsRes] = await Promise.all([
        api<{ data: MailResponse[] }>(
          "GET",
          `/api/tenants/${tenantId}/agents/instances/${instanceId}/mail?limit=100`,
        ),
        api<{ data: InferenceTurnResponse[] }>(
          "GET",
          `/api/tenants/${tenantId}/agents/instances/${instanceId}/turns?limit=100`,
        ),
      ]);

      if (cancelled) return;
      if (getMessages(instanceId).length > 0) return;

      const mailMessages: ChatMessage[] = mailRes.data
        .filter((m) => shouldShowMail(m))
        .map((m) => mailToMessage(m));

      const turnMessages: ChatMessage[] = turnsRes.data
        .map(turnToMessage)
        .filter((m): m is ChatMessage => m !== null);

      const all = [...mailMessages, ...turnMessages].sort((a, b) =>
        a.timestamp < b.timestamp ? -1 : a.timestamp > b.timestamp ? 1 : 0,
      );

      if (all.length > 0) {
        instanceMessages.set(instanceId, all);
        rerender();
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [isRunning, instanceId, tenantId]);

  // Open/close the EventSource based on instance running state.
  useEffect(() => {
    if (!isRunning) return;

    let cancelled = false;

    const close = openStream(
      `/api/tenants/${tenantId}/agents/instances/${instanceId}/events`,
      (raw) => {
        if (cancelled) return;

        if (!(sessionEndedEvent(raw) instanceof type.errors)) {
          queryClient.invalidateQueries({
            queryKey: ["tenants", tenantId, "instances"],
          });
          return;
        }

        // Hub-originated committed-state events: these are the only events
        // that push messages into the timeline. Handle them before checking
        // the InferenceEvent union to avoid namespace confusion.
        const mailEvent = MailDeliveredEvent(raw);
        if (!(mailEvent instanceof type.errors)) {
          const messages = getMessages(instanceId);
          const mailId = mailEvent.data.id;
          const already = messages.some(
            (m) => m.kind === "mail" && m.id === mailId,
          );
          if (!already) {
            const d = mailEvent.data;
            if (!shouldShowMail(d)) return;

            const isOutbound = d.direction === "outbound";

            const role: "user" | "assistant" = isOutbound
              ? "assistant"
              : "user";
            const firstSender = d.from?.[0];
            const sender: MailAddress = firstSender
              ? { name: firstSender.name ?? null, email: firstSender.email }
              : { name: null, email: "unknown" };
            const content = extractBodyText(d.bodyValues, d.textBody);
            const recipients: MailAddress[] = (d.to ?? []).map((r) => ({
              name: r.name ?? null,
              email: r.email,
            }));

            messages.push({
              kind: "mail",
              id: mailId,
              role,
              content,
              sender,
              recipients,
              timestamp: d.receivedAt,
              attachments: (d.attachments ?? []).map((att) => ({
                blobId: att.blobId,
                name: att.name ?? null,
                type: att.type,
                size: att.size,
              })),
            });
            rerender();
          }
          return;
        }

        const turnEvent = TurnCommittedEvent(raw);
        if (!(turnEvent instanceof type.errors)) {
          const messages = getMessages(instanceId);
          const { turnId, status, text, hadError, errors, toolErrors } =
            turnEvent.data;
          const isError = hadError || status === "failed";
          const already = messages.some(
            (m) => m.kind === "turn" && m.turnId === turnId,
          );
          if (!already && (text || isError || toolErrors.length > 0)) {
            messages.push({
              kind: "turn",
              turnId,
              content: text || "An error occurred during inference.",
              timestamp: new Date().toISOString(),
              ...(isError ? { isError: true } : {}),
              ...(errors.length > 0 ? { errors } : {}),
              ...(toolErrors.length > 0 ? { toolErrors } : {}),
            });
          }
          // Only clear the streaming buffer if it still holds text from the
          // committed turn. In multi-step tool loops, turn.committed for turn
          // N may arrive after deltas for turn N+1 have already started
          // populating the buffer with new content.
          const current = getStreaming(instanceId);
          if (!current || current === text) {
            instanceStreaming.set(instanceId, "");
          }
          instanceActivity.set(instanceId, null);
          rerender();
          return;
        }

        // Ephemeral state: inference events drive the streaming preview
        // and activity indicator only. They never push committed messages.
        const validated = InferenceEvent(raw);
        if (validated instanceof type.errors) return;
        const event: ValidInferenceEvent = validated as ValidInferenceEvent;
        switch (event.type) {
          case "inference.start":
            instanceActivity.set(instanceId, { type: "inferring" });
            rerender();
            break;
          case "inference.text.delta":
            instanceStreaming.set(
              instanceId,
              getStreaming(instanceId) + event.data.token,
            );
            instanceActivity.set(instanceId, null);
            rerender();
            break;
          case "inference.tool_call.start":
            instanceActivity.set(instanceId, {
              type: "tool_call",
              name: event.data.name,
            });
            rerender();
            break;
          case "tool.start":
            instanceActivity.set(instanceId, {
              type: "tool_running",
              name: event.data.call.name,
            });
            rerender();
            break;
          case "tool.done":
            instanceActivity.set(instanceId, null);
            rerender();
            break;
          case "inference.done":
            instanceActivity.set(instanceId, null);
            rerender();
            break;
          case "inference.error":
            instanceStreaming.set(instanceId, "");
            instanceActivity.set(instanceId, null);
            rerender();
            break;
          case "reactor.done":
            instanceStreaming.set(instanceId, "");
            instanceActivity.set(instanceId, null);
            rerender();
            break;
        }
      },
      { eventName: "agent.event" },
    );
    return () => {
      cancelled = true;
      close();
      instanceActivity.set(instanceId, null);
    };
  }, [isRunning, instanceId, tenantId, instance?.address]);

  const stopMut = useMutation({
    ...stopInstanceMutation(tenantId, queryClient),
    onSuccess: () => {
      clearInstanceState(instanceId);
      queryClient.invalidateQueries({
        queryKey: ["tenants", tenantId, "instances"],
      });
      queryClient.invalidateQueries({
        queryKey: ["tenants", tenantId, "agents"],
      });
      rerender();
    },
  });

  async function handleSendChat(e: React.FormEvent) {
    e.preventDefault();
    if (!chatInput.trim() || isSending) return;
    const userMessage = chatInput.trim();
    setChatInput("");
    setIsSending(true);
    try {
      await api(
        "POST",
        `/api/tenants/${tenantId}/agents/instances/${instanceId}/mail`,
        { content: userMessage },
      );
    } finally {
      setIsSending(false);
    }
  }

  useEffect(() => {
    chatPinnedRef.current = true;
  }, [instanceId]);

  useEffect(() => {
    if (!isRunning) return;
    const el = chatScrollRef.current;
    if (el && chatPinnedRef.current) {
      el.scrollTop = el.scrollHeight;
    }
  });

  if (isLoading) {
    return <div className="p-4 text-sm text-muted-foreground">Loading...</div>;
  }

  if (!instance) {
    return <div className="p-4 text-sm text-muted-foreground">Not found.</div>;
  }

  return (
    <div>
      <div className="mb-6">
        <Link
          to="/tenants/$tenantId/instances"
          params={{ tenantId }}
          className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="size-3.5" />
          Instances
        </Link>
      </div>

      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-lg font-semibold">
            <Link
              to="/tenants/$tenantId/agents/$agentId"
              params={{ tenantId, agentId: instance.agentId }}
              className="text-primary hover:underline"
            >
              {instance.agentName}
            </Link>
          </h2>
          <p className="mt-1 font-mono text-xs text-muted-foreground">
            {instance.address}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {isRunning && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => stopMut.mutate(instanceId)}
              disabled={stopMut.isPending}
            >
              {stopMut.isPending ? "Stopping..." : "Stop"}
            </Button>
          )}
        </div>
      </div>

      <div className="mt-6">
        <dl className="overflow-hidden rounded-lg border">
          <Row label="Status">
            <StatusBadge status={displayStatus} />
          </Row>
          <Row label="Instance ID">
            <span className="font-mono text-xs">{instance.id}</span>
          </Row>
          {instance.kernelId && (
            <Row label="Kernel ID">
              <span className="font-mono text-xs">{instance.kernelId}</span>
            </Row>
          )}
          {instance.sidecarId && (
            <Row label="Sidecar ID">
              <span className="font-mono text-xs">{instance.sidecarId}</span>
            </Row>
          )}
          <Row label="Created">
            {new Date(instance.createdAt).toLocaleString()}
          </Row>
          {instance.endedAt && (
            <Row label="Ended">
              {new Date(instance.endedAt).toLocaleString()}
            </Row>
          )}
        </dl>
      </div>

      <MutationError error={stopMut.error} />

      {isRunning && (
        <div className="mt-8">
          <h3 className="text-sm font-semibold">Chat</h3>
          <div className="mt-3 flex flex-col gap-3 rounded-lg border p-4">
            <div
              ref={chatScrollRef}
              onScroll={(e) => {
                const el = e.currentTarget;
                chatPinnedRef.current =
                  el.scrollTop + el.clientHeight >= el.scrollHeight - 24;
              }}
              className="flex h-64 flex-col gap-2 overflow-y-auto"
            >
              {getMessages(instanceId).length === 0 &&
              !getStreaming(instanceId) ? (
                <p className="text-sm text-muted-foreground">
                  Start a conversation with the agent...
                </p>
              ) : (
                getMessages(instanceId).map((msg) => {
                  const isUser = msg.kind === "mail" && msg.role === "user";
                  const isAssistantTurn = msg.kind === "turn";
                  const isAssistantMail =
                    msg.kind === "mail" && msg.role === "assistant";
                  const isAssistant = isAssistantTurn || isAssistantMail;
                  const agentRecipient =
                    isAssistantMail && msg.kind === "mail"
                      ? resolveAgentRecipient(msg.recipients)
                      : null;
                  const agentSender =
                    isUser && msg.kind === "mail"
                      ? resolveAgentAddress(msg.sender)
                      : null;
                  const isOutboundInterAgent = agentRecipient !== null;
                  const isInboundInterAgent = agentSender !== null;
                  const isInterAgentMail =
                    isOutboundInterAgent || isInboundInterAgent;

                  const label = msg.isError
                    ? "Error"
                    : isInterAgentMail
                      ? null
                      : isAssistant
                        ? "Agent"
                        : msg.kind === "mail"
                          ? parseFromHeader(formatAddress(msg.sender))
                          : null;

                  return (
                    <div
                      key={msg.kind === "mail" ? msg.id : msg.turnId}
                      className={`rounded p-2 text-sm ${
                        msg.isError
                          ? "mr-8 border border-destructive/30 bg-destructive/10 text-destructive"
                          : isInterAgentMail
                            ? "mx-8 border border-border bg-muted/30 text-muted-foreground"
                            : isUser
                              ? "bg-muted ml-8"
                              : "mr-8 bg-primary/10"
                      }`}
                    >
                      {isOutboundInterAgent && agentRecipient !== null ? (
                        <div className="mb-1 inline-flex items-center gap-1 text-xs">
                          <Mail className="size-3" />
                          <span>
                            Sent mail to{" "}
                            <Link
                              to="/tenants/$tenantId/instances/$instanceId"
                              params={{
                                tenantId,
                                instanceId: agentRecipient.instanceId,
                              }}
                              className="font-medium text-primary underline"
                            >
                              {agentRecipient.label}
                            </Link>
                          </span>
                        </div>
                      ) : isInboundInterAgent && agentSender !== null ? (
                        <div className="mb-1 inline-flex items-center gap-1 text-xs">
                          <Mail className="size-3" />
                          <span>
                            Received mail from{" "}
                            <Link
                              to="/tenants/$tenantId/instances/$instanceId"
                              params={{
                                tenantId,
                                instanceId: agentSender.instanceId,
                              }}
                              className="font-medium text-primary underline"
                            >
                              {agentSender.label}
                            </Link>
                          </span>
                        </div>
                      ) : label ? (
                        <span className="font-medium">{label}: </span>
                      ) : null}
                      {isInterAgentMail ? (
                        <div className="text-xs whitespace-pre-wrap">
                          {msg.content}
                        </div>
                      ) : (
                        msg.content
                      )}
                      {msg.kind === "turn" &&
                        msg.errors &&
                        msg.errors.length > 0 && (
                          <div className="mt-1.5 space-y-1">
                            {msg.errors.map((err, i) => (
                              <div
                                key={i}
                                className="rounded border border-destructive/30 bg-destructive/10 px-2 py-1 text-xs text-destructive"
                              >
                                <span className="font-medium">
                                  {err.category}:
                                </span>{" "}
                                {err.message}
                              </div>
                            ))}
                          </div>
                        )}
                      {msg.kind === "turn" &&
                        msg.toolErrors &&
                        msg.toolErrors.length > 0 && (
                          <div className="mt-1.5 space-y-1">
                            {msg.toolErrors.map((err, i) => (
                              <div
                                key={i}
                                className="rounded border border-amber-500/30 bg-amber-500/10 px-2 py-1 text-xs text-amber-700 dark:text-amber-400"
                              >
                                <span className="font-medium">
                                  Tool Error ({err.name}):
                                </span>{" "}
                                {err.content}
                              </div>
                            ))}
                          </div>
                        )}
                      {msg.kind === "mail" && msg.attachments.length > 0 && (
                        <div className="mt-1 flex flex-col gap-0.5">
                          {msg.attachments.map((att) => (
                            <a
                              key={att.blobId}
                              href={`/api/tenants/${tenantId}/agents/instances/blobs/${att.blobId}`}
                              target="_blank"
                              rel="noreferrer"
                              className="inline-flex items-center gap-1 text-xs text-primary underline"
                            >
                              <Paperclip className="size-3" />
                              {att.name ?? att.blobId}
                            </a>
                          ))}
                        </div>
                      )}
                    </div>
                  );
                })
              )}
              {getStreaming(instanceId) && (
                <div className="mr-8 rounded bg-primary/10 p-2 text-sm">
                  <span className="font-medium">Agent:</span>{" "}
                  {getStreaming(instanceId)}
                </div>
              )}
              {(() => {
                const activity = instanceActivity.get(instanceId) ?? null;
                if (activity !== null) {
                  const label =
                    activity.type === "inferring"
                      ? "Thinking..."
                      : activity.type === "tool_call"
                        ? `Calling ${activity.name}...`
                        : `Running ${activity.name}...`;
                  return (
                    <div className="text-sm text-muted-foreground">{label}</div>
                  );
                }
                if (isSending && !getStreaming(instanceId)) {
                  return (
                    <div className="text-sm text-muted-foreground">
                      Sending...
                    </div>
                  );
                }
                return null;
              })()}
            </div>

            <form onSubmit={handleSendChat} className="flex gap-2">
              <Input
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                placeholder="Type a message..."
                disabled={isSending}
              />
              <Button type="submit" disabled={isSending || !chatInput.trim()}>
                Send
              </Button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
